### ISSUE TITLE
Database initialisation

### ISSUE THREAD

**Issue by oliverroick** [earth-genome/foodtwin-global-app#10]
- [x] Setup docker image
- [x] Add basic database schema
- [x] Add DB migrations using Prisma
- [x] Add database to staging website
- [x] Configure Prisma client setup on Amplify
- [x] Ingest data to staging website

**Comment by vgeorge** [comment]
@oliverroick status update on this:

- A RDS instance was created and `DATABASE_URL` was set as an environment variable on Amplify
- The OpenSSL version was downgraded [here](https://github.com/earth-genome/foodtwin-global-app/blob/00d6285d8904fee1255b0c86470f460d1a0e9b16/prisma/schema.prisma#L4) because `rhel-openssl-3.0.x` is not available during runtime (there is probably a better approach for this, but I couldn't find how to upgrade the runtime environment)
- In the logs, there is an error with the Prisma client not having the proper `DATABASE_URL` set. I added it to the Environment Variables section in Amplify, but I am not sure why it is not working now

**Comment by vgeorge** [comment]
This is completed, the staging website is now serving vector tiles from the RDS instance:

https://develop.d2wdw1hzf2w0yx.amplifyapp.com/
