### ISSUE TITLE
World View

### ISSUE THREAD

**Issue by oliverroick** [earth-genome/foodtwin-global-app#5]
**Acceptance criteria**

- The globe shows production areas, ports and shipping routes
- Hovering over a production area, port or shipping route shows a popover with its name
- Clicking on  a production area, port or shipping route opens the corresponding detail page

**Comment by vgeorge** [comment]
I'm renaming this to World View. We are not pursuing the Globe 3d rendering due to:

- Deck.gl's [globe view](https://deck.gl/docs/api-reference/core/globe-view) is experimental and does not support MVT well
- Mapbox's globe view can render MVT, but we are planning to render particles with Deck.gl, which [doesn't support Mapbox's globe view](https://github.com/visgl/react-map-gl/issues/2091#issuecomment-1366837554)

Considering that MapLibre apparently covers all the functionality we need for the project, and its [Deck.gl integration](https://deck.gl/docs/developer-guide/base-maps/using-with-maplibre) seems stable, an implementation of the World View with MapLibre + Deck.gl seems the way to go.

cc @cameronkruse @faustoperez @oliverroick @wrynearson

**Comment by wrynearson** [comment]
@oliverroick will break this out into separate tickets, then will close this ticket
