### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by oliverroick** [earth-genome/foodtwin-global-app#51]
**Acceptance criteria**

- [x] A “Search the map” button is added
- [x] Clicking the button opens the search tool
- [x] A form field allows entering a term
- [x] At least three letters are required for the search to start
- [x] The search results list producing areas and ports matching the entered search query in alphabetical order
- [x] Clicking a result opens the page for the corresponding area or port
- [x] A message is shown when there are no results matching the entered terms. 
- [x] Debounce API requests

**Comment by vgeorge** [comment]
To close this, I believe we need to add proximity search to handle non-English city names like São Paulo, München, etc, as suggested in https://github.com/earth-genome/foodtwin-global-app/pull/66#issue-2556852043. The PostgreSQL extension [pgtrgm](https://www.postgresql.org/docs/16/pgtrgm.html) seems a good choice.

cc @oliverroick @wrynearson

**Comment by wrynearson** [comment]
@vgeorge I opened https://github.com/earth-genome/foodtwin-global-app/issues/68 in case that becomes more difficult than it sounds like it'd be (enabling it in the DB). From that perspective, I think we can close this because search is working for most use cases.

One other thing to flag – according to the [designs](https://www.figma.com/design/zz7755JriAt4vKJsdV3Dcr/Global-Food-Twin?node-id=1227-37782&t=o5pM7Qyap4TTdqdE-4), the search results should be `Region Name, XX`, with `XX` being the 2-digit country code. Currently, we're not using that value. Some results have `_Country` while others don't have any indication of the country.

<img width="738" alt="image" src="https://github.com/user-attachments/assets/31112ed9-a81b-4c01-a076-b7c370128ab2">
